# Generated by Django 4.2.4 on 2023-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150, null=True)),
                ('class_attended', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('course', models.CharField(max_length=150, null=True)),
                ('number_of_subjects', models.IntegerField(default=0)),
                ('subject1', models.CharField(max_length=150, null=True)),
                ('subject2', models.CharField(max_length=150, null=True)),
                ('subject3', models.CharField(max_length=150, null=True)),
                ('subject4', models.CharField(max_length=150, null=True)),
                ('subject5', models.CharField(max_length=150, null=True)),
                ('subject6', models.CharField(max_length=150, null=True)),
                ('subject7', models.CharField(max_length=150, null=True)),
                ('subject8', models.CharField(max_length=150, null=True)),
                ('subject9', models.CharField(max_length=150, null=True)),
                ('subject10', models.CharField(max_length=150, null=True)),
                ('subject11', models.CharField(max_length=150, null=True)),
                ('subject12', models.CharField(max_length=150, null=True)),
                ('subject13', models.CharField(max_length=150, null=True)),
                ('subject14', models.CharField(max_length=150, null=True)),
                ('subject15', models.CharField(max_length=150, null=True)),
                ('subject16', models.CharField(max_length=150, null=True)),
                ('subject17', models.CharField(max_length=150, null=True)),
                ('subject18', models.CharField(max_length=150, null=True)),
                ('subject19', models.CharField(max_length=150, null=True)),
                ('subject20', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'student_courses',
            },
        ),
    ]
